server:
  port: 8809
  
spring:
 application:
  name: gxCaptureWorkflow
 profiles:
  active: DEV
mail:
 error:
  notification:
   from: rramreddybai@galaxe.com
   to: rramreddybai@galaxe.com
   subject: "Error alert: [DEV] workflow application failure detected"
 
---
spring:
 profiles: DEV
 datasource:
  #url: jdbc:postgresql://10.3.10.150:5432/gxWorkflow?currentSchema=workflowqa
  url: jdbc:postgresql://10.3.10.150:5432/gxWorkflow?currentSchema=workflowtest
  username: gxworkflow
  password: gxworkflow@321
  type: com.zaxxer.hikari.HikariDataSource
  hikari:
   connection-timeout: 15000
   maximum-pool-size: 11
   idleTimeout: 10000
   maxLifetime: 1800000
 mail.templates-location: C:\Users\ksrinivasa\OneDrive - GalaxE. Solutions, Inc\Desktop\GxCapture Product\GxWorkflow\src\main\resources\templates
 mail-smtp-server: smtp.galaxe.com
 mail.host: smtp.galaxe.com
 jpa:
    hibernate:
      ddlAuto: none
      naming:
       implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    database: postgresql
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.legacy_limit_handler: true
      hibernate.proc.param_null_passing: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
 
 servlet:
  multipart:
   max-file-size: 100MB
   max-request-size: 100MB
---